apiVersion: v1
kind: Service
metadata:
  namespace: treehub
  name: ghost
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 2368
  selector:
    app: ghost
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: treehub
  name: ghost
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - name: ghost
        image: ghost:0.11.7
        imagePullPolicy: Always
        env:
        - name: NODE_ENV
          value: production
        ports:
        - containerPort: 2368
        readinessProbe:
          httpGet:
            path: /favicon.ico
            port: 2368
          periodSeconds: 5
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 10
        volumeMounts:
        - mountPath: /var/lib/ghost
          name: data
      volumes:
      - name: data
        gcePersistentDisk:
          pdName: ghost
          fsType: ext4
